accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"


urlpatterns = [
    path("login/", views.account_login, name="login"),
    path("signup/", views.account_signup, name="signup"),
    path("logout/", views.account_logout, name="logout"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path('', views.article_list, name="list"),
    path('create/', views.article_create, name="create"),
    path('<slug:slug>/', views.article_detail, name="detail"),
    path('delete/<slug:slug>/', views.delete_article, name="delete"),

]

contact/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.contact_create_list, name="create_contact_list")
    ]

djangonutic/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views
# from contact import views as contact_veiws
from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSitemap

sitemaps = {
    'static': StaticViewSitemap
}

urlpatterns = [
    path('', include("contact.urls"), name='contact'),
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include("accounts.urls")),
    path('articles/', include("articles.urls"), name='articles'),
    path('contact/', include("contact.urls"), name='contact'),
    path('404/', views.view_404, name='404'),
    path('manifest.json', views.view_manifest_json, name='manifest'),
    path('robots.txt', views.view_robot_txt, name='robots'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    # path('', views.homepage),
    # path('', include("articles.urls")),



]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base_layout.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- bad way of calling static files -->
    <!-- <link rel="stylesheet" href="/static/styles.css"> -->
    <link rel="stylesheet" href="{%static 'styles.css'%}">
    <link rel="shortcut icon" type="image/png" href="{%static 'logo.svg'%}" />
    <link rel="icon" type="image/x-icon" href="{%static 'logo.svg'%}">
    <link rel="manifest" href="{% url 'manifest'%}">

    <title>contact app</title>

</head>

<body>
    <div class="wrepper">
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        {% if request.user.is_superuser %}

                        <li>
                            <a href="{%url 'accounts:signup'%}">Signup</a>
                        </li>
                        {% endif %}
                    <li>
                        <form class="logout-link" action="{%url 'accounts:logout'%}" method="post">
                            {% csrf_token %}
                            <button type="submit">LogOut</button>
                        </form>
                    </li>
                    <li>
                        <a href="{%url 'articles:create'%}" class="highlight">Add file</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{%url 'accounts:login'%}">LogIn</a>
                    </li>
                    {% endif %}


                </ul>
            </nav>

        </header>

        <!-- on big screan -->
        <button class="menu">☰</button>

        <nav class="banner">
            <ul>
                
                
                
                <a href="{% url 'articles:list' %}">
                    <li><img src="{%static 'navIcons/achievements.svg'%}" alt="achievements icon" class="navIcon"><span>Files</span></li>
                </a>
                
               <a href="{% url 'create_contact_list' %}">
                    <li><img src="{%static 'navIcons/contact.svg'%}" alt="contact icon" class="navIcon"><span>Chat</span></li>
                </a>
            
            </ul>
        </nav>










        {% block content %}

        {% endblock content %}
    </div>
    <script src="{%static 'app.js'%}"></script>
</body>

</html>